S3 us5.1 login form
WildCodeSchool-2023-09/remfr-php-p3-externatic pull request #10
Opened 2023-12-17 12:39 UTC by Sinezis

2023-12-17 18:53 UTC, kykileur requested changes
y'a une erreur

2023-12-17 20:42 UTC, lderi78 approved these changes

2023-12-17 22:07 UTC, JessKel approved these changes
Après relecture, c'est ok pour moi. On a parlé de la modif qui sera faite dans la prochaine PR

2023-12-17 22:07 UTC, JessKel commented on src/Controller/OfferController.php
Tu pourrais changer les route puisque tu as définis une route /offer. Pour new, je mettrai name: 'new',  ainsi que pour les autres. Ce sera plus simple et on gardera une harmonie dans le nom des routes.

2023-12-19 14:06 UTC, vincentr-wcs approved these changes

2023-12-19 14:08 UTC, Kyliann-Fernandes approved these changes

2023-12-19 14:08 UTC, merged