Pages twig des cartes Offers et description des offers + Route de base
WildCodeSchool-2023-09/remfr-php-p3-externatic pull request #15
Opened 2023-12-20 08:30 UTC by lderi78

2023-12-20 09:03 UTC, JessKel requested changes
Voir mes commentaires dans les fichiers

2023-12-20 09:03 UTC, JessKel commented on src/Controller/OffersController.php
Pour le controller, il a déjà été fait par Adrien avec toutes les routes et les liens nécessaires. Il faudra donc faire appel à celui qu'on récupère. Du coup, tu peux le supprimer.

2023-12-20 09:03 UTC, JessKel commented on templates/offers/index.html.twig
Au niveau de la route pour visualiser l'offre en détails, il faut mettre {{ path('app_offer_show', {'id': offer.id}) }} pour appeler l'offre en question.

2023-12-20 09:03 UTC, JessKel commented on templates/offers/index2.html.twig
Concernant la redirection sur la page de liste des offres, il faudra mettre : {{ path('app_offer_index') }}
Sinon, en principe, il vaut mieux mettre le CSS dans un fichier à part que tu pourrais appeler offers.scss à mettre dans le dossier assets>styles et bien sûr penser à mettre le lien de ce fichier dans app.scss en @import

2023-12-21 13:12 UTC, Sinezis reviewed
Je rejoins jessica dans sa review

2024-01-08 08:41 UTC, closed without merging

2024-01-08 08:41 UTC, JessKel commented
Page revue et terminée faisant l'objet d'une nouvelle PR