ajout upload de CV
WildCodeSchool-2023-09/remfr-php-p3-externatic pull request #28
Opened 2024-01-05 17:12 UTC by JessKel

2024-01-06 15:51 UTC, Sinezis approved these changes
Tout est ok pour moi

2024-01-06 15:53 UTC, Sinezis requested changes
Il ne manque que la fermeture d'accolades

2024-01-06 15:53 UTC, Sinezis commented on src/Entity/User.php
> +
Il manque une fermeture d'accolades

2024-01-08 08:50 UTC, JessKel commented on src/Entity/User.php
> +
c'est fait

2024-01-08 13:19 UTC, Sinezis approved these changes
maintenant tout me parait good!

2024-01-08 13:23 UTC, Kyliann-Fernandes approved these changes

2024-01-08 17:33 UTC, merged