la page process de la bdd
WildCodeSchool-2023-09/remfr-php-p3-externatic pull request #3
Opened 2023-12-13 15:58 UTC by kykileur

2023-12-13 16:01 UTC, Sinezis requested changes
process et statut seront des tableaux de constantes et non des strings
à part ça c'est correct
bien joué bg
continue comme ça
vive kyky
t'es une machine

2023-12-13 16:06 UTC, JessKel requested changes
comme discuté avec Adrien, c'est pas bon. Faut changer le format du statut : INT et ajouter une constante

2023-12-14 09:42 UTC, JessKel approved these changes
Pour moi c'est ok maintenant

2023-12-14 14:57 UTC, Sinezis reviewed
maintenant c'est all good

2023-12-14 15:04 UTC, Sinezis approved these changes

2023-12-14 15:07 UTC, yavuzkutuk approved these changes

2023-12-14 15:07 UTC, yavuzkutuk commented
@kykileur tu veux merge sur la main et non la dev

2023-12-14 15:13 UTC, merged