Pages twig : ml,cgu & cookies linkés au footer
WildCodeSchool-2023-09/remfr-php-p3-externatic pull request #41
Opened 2024-01-11 14:09 UTC by lderi78

pages twig : ml,cgu & cookies linkés au footer

2024-01-11 14:35 UTC, JessKel approved these changes
ça parait ok. Bon boulot

2024-01-11 18:29 UTC, Kyliann-Fernandes approved these changes

2024-01-12 07:48 UTC, Sinezis reviewed
Il y a des erreurs de code, cf le mp que je t'ai envoyé

2024-01-15 09:22 UTC, Sinezis requested changes

2024-01-15 09:22 UTC, Sinezis commented on src/DataFixtures/CompanyFixtures.php
ton erreur est ici, ligne 8
tu dois retirer ton saut de ligne

2024-01-15 11:33 UTC, closed without merging