Update fixtures
WildCodeSchool-2023-09/remfr-php-p3-externatic pull request #46
Opened 2024-01-12 15:16 UTC by Sinezis

2024-01-12 17:07 UTC, Kyliann-Fernandes approved these changes

2024-01-12 22:29 UTC, JessKel approved these changes
ok pour moi

2024-01-14 11:44 UTC, vincentr-wcs requested changes

2024-01-14 11:44 UTC, vincentr-wcs commented on src/DataFixtures/UserFixtures.php
> +        $user = new User();
Dans ce fichier tu redéfinie plusieurs la même variable $user. 
Il faudrait plus faire : 
```suggestion
        $admin = new User();
        $admin->setEmail($faker->email());
```

2024-01-14 11:44 UTC, vincentr-wcs commented on src/DataFixtures/UserFixtures.php
> +            $user = new User();
```suggestion
            $collaborateur = new User();
            $collaborateur->setEmail($faker->email())
            ...
```

2024-01-14 11:44 UTC, vincentr-wcs commented on src/DataFixtures/UserFixtures.php
> +        $collaborateur = [];
```suggestion
       $collaborateurs = [];
```

2024-01-14 11:44 UTC, vincentr-wcs commented on src/DataFixtures/UserFixtures.php
>              $user = new User();
```suggestion
            $candidat = new User();
            $candidat->setEmail($faker->email());
            ...
```

2024-01-14 13:43 UTC, Sinezis commented on src/DataFixtures/UserFixtures.php
>              $user = new User();
@vincentr-wcs changements faits!

2024-01-14 13:44 UTC, Sinezis commented on src/DataFixtures/UserFixtures.php
> +        $user = new User();
changements faits!

2024-01-14 13:44 UTC, Sinezis commented on src/DataFixtures/UserFixtures.php
> +            $user = new User();
changements faits!

2024-01-14 13:44 UTC, Sinezis commented on src/DataFixtures/UserFixtures.php
> +        $collaborateur = [];
@vincentr-wcs changements faits!

2024-01-15 08:06 UTC, vincentr-wcs approved these changes

2024-01-15 08:06 UTC, merged