Suppression process
WildCodeSchool-2023-09/remfr-php-p3-externatic pull request #62
Opened 2024-01-24 15:19 UTC by Sinezis

2024-01-24 15:40 UTC, Kyliann-Fernandes approved these changes

2024-01-24 15:40 UTC, JessKel approved these changes
Nickel

2024-01-24 16:12 UTC, lderi78 approved these changes

2024-01-25 08:28 UTC, vincentr-wcs requested changes

2024-01-25 08:28 UTC, vincentr-wcs commented on src/Controller/ProcessController.php
> -        if ($this->isCsrfTokenValid('delete' . $process->getId(), $request->request->get('_token'))) {
Pourquoi enlever la méthode qui permet de vérifier si y'a un jeton valide CSRF et donc se protéger contre les attaques CSRF ?

2024-01-25 08:28 UTC, vincentr-wcs commented on src/Form/ProcessPublicType.php
> +            'csrf_protection' => false,
Pourquoi tu désactives la protection csrf ?

2024-01-25 08:28 UTC, vincentr-wcs commented on templates/process_public/_delete_form.html.twig
> -	<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ process.id) }}">
Idem

2024-01-25 14:43 UTC, Sinezis commented on src/Controller/ProcessController.php
> -        if ($this->isCsrfTokenValid('delete' . $process->getId(), $request->request->get('_token'))) {
parce que ça bug et que c'est le seul moyen que j'ai trouvé

2024-01-26 08:06 UTC, vincentr-wcs approved these changes

2024-01-26 08:06 UTC, merged