connexion du formulaire Users à la BDD
WildCodeSchool-2023-09/remfr-php-p3-externatic pull request #9
Opened 2023-12-16 13:18 UTC by Sinezis

2023-12-17 18:56 UTC, kykileur approved these changes

2023-12-17 21:21 UTC, JessKel commented on src/DataFixtures/UsersFixtures.php
Pourquoi tu as supprimé ce fichier ?

2023-12-17 21:35 UTC, JessKel approved these changes
J'ai tout regardé et cela me parait correct.

2023-12-18 13:39 UTC, vincentr-wcs requested changes
Franchement beau boulot ! Pense à bien tout sécuriser dans une prochaine feature au niveau du user ce que tu aurais pu faire avec la commande make:auth. Il faut juste changer entity Users en singulier

2023-12-18 13:39 UTC, vincentr-wcs commented on src/Entity/Users.php
>  class Users
Faut pas mettre le nom des entity au pluriel

2023-12-18 13:39 UTC, vincentr-wcs commented on src/Entity/Users.php
> +    public const MARITAL_STATUS = [
Je l'aurais mis en private je ne pense pas qu'elle soit utilisé hors de la class non ?

2023-12-18 15:59 UTC, Sinezis commented on src/Entity/Users.php
>  class Users
Je sais j'ai commencé à changer!
J'essaie de changer au fur et à mesure pour ne pas devenir dingue haha

2023-12-18 15:59 UTC, Sinezis commented on src/Entity/Users.php
> +    public const MARITAL_STATUS = [
je vais regarder ça!

2023-12-18 16:15 UTC, Sinezis commented on src/DataFixtures/UsersFixtures.php
Vu en vocal!

2023-12-18 16:22 UTC, Sinezis commented on src/Entity/Users.php
> +    public const MARITAL_STATUS = [
Si je modifie j'ai une erreur qui pop dans les formulaires twig

2023-12-19 14:08 UTC, merged